/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as DIDRegistrarContractJson } from "../DIDRegistrar.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace DIDRegistrarTypes {
  export type Fields = {
    didRecordContractId: HexString;
  };

  export type State = ContractState<Fields>;
}

class Factory extends ContractFactory<
  DIDRegistrarInstance,
  DIDRegistrarTypes.Fields
> {
  consts = { ErrorCodes: { InvalidCaller: BigInt(0) } };

  at(address: string): DIDRegistrarInstance {
    return new DIDRegistrarInstance(address);
  }

  tests = {
    getDIDRecordContractId: async (
      params: TestContractParams<
        DIDRegistrarTypes.Fields,
        { identity: Address; caller: Address }
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getDIDRecordContractId", params);
    },
    register: async (
      params: TestContractParams<
        DIDRegistrarTypes.Fields,
        { identity: Address }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "register", params);
    },
    setAttribute: async (
      params: TestContractParams<
        DIDRegistrarTypes.Fields,
        { identity: Address; name: bigint; value: HexString; validity: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "setAttribute", params);
    },
    revokeAttribute: async (
      params: TestContractParams<
        DIDRegistrarTypes.Fields,
        { identity: Address; name: bigint; value: HexString }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "revokeAttribute", params);
    },
  };
}

// Use this object to test and deploy the contract
export const DIDRegistrar = new Factory(
  Contract.fromJson(
    DIDRegistrarContractJson,
    "",
    "993156a0ff3235add6408b6d054b461ee1ee1105dffd648750162af20c5cf649"
  )
);

// Use this class to interact with the blockchain
export class DIDRegistrarInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DIDRegistrarTypes.State> {
    return fetchContractState(DIDRegistrar, this);
  }
}
