/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as SetAttributeScriptJson } from "../SetAttribute.ral.json";
import { default as RevokeAttributeScriptJson } from "../RevokeAttribute.ral.json";

export const SetAttribute = new ExecutableScript<{
  registrar: HexString;
  identity: Address;
  name: bigint;
  value: HexString;
  validity: bigint;
}>(Script.fromJson(SetAttributeScriptJson));
export const RevokeAttribute = new ExecutableScript<{
  registrar: HexString;
  identity: Address;
  name: bigint;
  value: HexString;
}>(Script.fromJson(RevokeAttributeScriptJson));
